dbt_project:
  outputs:
    dev:
      account: JVILJLG-QC75251
      database: SUNIL_DBT_CORE
      password: Tiku##07051982
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: sknando
      warehouse: COMPUTE_WH
  target: dev
